# What is NumPy and why is it important in data analysis?

In [1]:
!pip install numpy

     ---------------------------------------- 13.1/13.1 MB 8.3 MB/s eta 0:00:00



[notice] A new release of pip available: 22.3 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
# Create a sample array
arr = np.array([1, 2, 3, 4, 5])

# Perform some basic operations
print("Original array:", arr) # print the original array
print("Array mean:", np.mean(arr)) # print the mean of the array
print("Array sum:", np.sum(arr)) # print the sum of the array
print("Array squarred:", np.square(arr)) # print the squared array

# Create a 2D array
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("\n2D Array:")
print(matrix) # print the 2D array
print("Matrix transpose:")
print(matrix.T) # print the transpose of the matrix

standard_deviation = np.std(arr)
print("Standard deviation:", standard_deviation) # print the standard deviation of the array


Original array: [1 2 3 4 5]
Array mean: 3.0
Array sum: 15
Array squarred: [ 1  4  9 16 25]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Standard deviation: 1.4142135623730951


# NumPy Arrays:

In [4]:
# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])

print("\n 1D Array:", arr1) # print the 1D array


 1D Array: [1 2 3 4 5]


In [5]:
# Create a 2D array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print("\n 2D Array:")
print(arr2) # print the 2D array


 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Create a zero array
zero_array = np.zeros(5)
print("\n Zero Array:")
print(zero_array) # print the zero array


 Zero Array:
[0. 0. 0. 0. 0.]


In [7]:
# Create with one
one_array = np.ones((2,3))
print("\n One Array:")
print(one_array) # print the one array



 One Array:
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# Indexing in 1D Arrays
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr) # print the original array
print("First element:", arr[0]) # print the first element of the array
print("Last element:", arr[-1]) # print the last element of the array
print("Index elements 1 to 3:", arr[1:4]) # print the slice of the array


Original array: [10 20 30 40 50]
First element: 10
Last element: 50
Index elements 1 to 3: [20 30 40]


In [9]:
# Indexing in 2D Arrays
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original matrix:")
print(matrix)
print("Element in row 1, column 2:", matrix[1,2]) 
print("Second row:", matrix[1]) 
print("First column:", matrix[:,0]) 


Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element in row 1, column 2: 6
Second row: [4 5 6]
First column: [1 4 7]


In [27]:
#Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr) 
print("Elements greater than 5:", arr[arr > 5]) 
print("Even Elements:", arr[arr % 2 == 0]) 

Original array: [1 2 3 4 5]
Elements greater than 5: []
Even Elements: [2 4]


# Mathematical Operations with Numpy

In [ ]:
# Arithmetic operations with arrays
print("\nArray + 2:", arr + 2) 
print("Array * 3:", arr * 3) 
print("Array ** 2:", arr ** 2) 


Array + 2: [3 4 5 6 7]
Array * 3: [ 3  6  9 12 15]
Array ** 2: [ 1  4  9 16 25]


In [29]:
# Mathematical functions
print ("\nSquare root of array:", np.sqrt(arr))
print("Exponential of array:", np.exp(arr))
print("Sin of array:", np.sin(arr))


Square root of array: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential of array: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sin of array: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


# Basic statistics with Numpy

In [30]:
# Basic statistics with Numpy
print("\nMean of array:", np.mean(arr))
print("Standard deviation of array:", np.std(arr))
print("Maximum value:", np.max(arr))
print("Minimum value:", np.min(arr))


Mean of array: 3.0
Standard deviation of array: 1.4142135623730951
Maximum value: 5
Minimum value: 1


In [24]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [31]:
help(np.mean)

Help on _ArrayFunctionDispatcher in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
    Compute the arithmetic mean along the specified axis.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.
    
        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.  For integer inputs, the 

# Other manipulations - similar to sets in mathematics

In [32]:
# transpose
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Original matrix:")
print(matrix)
print("Transpose of matrix:")
print(matrix.T)

Original matrix:
[[1 2 3]
 [4 5 6]]
Transpose of matrix:
[[1 4]
 [2 5]
 [3 6]]


In [34]:
# Array Concatenation
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("\n Horizontal concatenation:", np.concatenate((arr1, arr2)))
print("\n Vertical concatenation:\n", np.vstack((arr1, arr2)))



 Horizontal concatenation: [1 2 3 4 5 6]

 Vertical concatenation:
 [[1 2 3]
 [4 5 6]]
