# What is NumPy and why is it important in data analysis?

In [13]:
!pip install numpy

In [6]:
import numpy as np

In [17]:
# Create a sample array
arr = np.array([1, 2, 3, 4, 5])

# Perform some basic operations
print("Original array:", arr) # print the original array
print("Array mean:", np.mean(arr)) # print the mean of the array
print("Array sum:", np.sum(arr)) # print the sum of the array
print("Array squarred:", np.square(arr)) # print the squared array

# Create a 2D array
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("\n2D Array:")
print(matrix) # print the 2D array
print("Matrix transpose:")
print(matrix.T) # print the transpose of the matrix

standard_deviation = np.std(arr)
print("Standard deviation:", standard_deviation) # print the standard deviation of the array


Original array: [1 2 3 4 5]
Array mean: 3.0
Array sum: 15
Array squarred: [ 1  4  9 16 25]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Standard deviation: 1.4142135623730951


# NumPy Arrays:

In [18]:
# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])

print("\n 1D Array:", arr1) # print the 1D array


 1D Array: [1 2 3 4 5]


In [19]:
# Create a 2D array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print("\n 2D Array:")
print(arr2) # print the 2D array


 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
# Create a zero array
zero_array = np.zeros(5)
print("\n Zero Array:")
print(zero_array) # print the zero array


 Zero Array:
[0. 0. 0. 0. 0.]


In [25]:
# Create with one
one_array = np.ones((2,3))
print("\n One Array:")
print(one_array) # print the one array



 One Array:
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Indexing in 1D Arrays
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr) # print the original array
print("First element:", arr[0]) # print the first element of the array
print("Last element:", arr[-1]) # print the last element of the array
print("Index elements 1 to 3:", arr[1:4]) # print the slice of the array


Original array: [10 20 30 40 50]
First element: 10
Last element: 50
Index elements 1 to 3: [20 30 40]


In [27]:
# Indexing in 2D Arrays
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original matrix:")
print(matrix)
print("Element in row 1, column 2:", matrix[1,2]) 
print("Second row:", matrix[1]) 
print("First column:", matrix[:,0]) 


Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element in row 1, column 2: 6
Second row: [4 5 6]
First column: [1 4 7]


In [33]:
#Boolean Indexing
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original array:", arr) 
print("Elements greater than 5:", arr[arr > 5]) 
print("Even Elements:", arr[arr % 2 == 0]) 

Original array: [1 2 3 4 5 6 7 8 9]
Elements greater than 5: [6 7 8 9]
Even Elements: [2 4 6 8]
